-- ============================================================================
-- DECYZJA OTWARTA §13.7 planu — EXECUTE na public.get_order_stats()
-- ⛔ PLIK ZABLOKOWANY DECYZYJNIE — nie jest migracją i nie wolno go wykonać.
-- Leży POZA supabase/migrations/ celowo (jak orders_status_check_confirmed.sql).
--
-- Stan faktyczny (zweryfikowane review T8, nit-1): kodowa połowa WARIANTU 1
-- JUŻ ISTNIEJE. `api/server-vercel.js:565` woła
-- `privateServerClient.rpc('get_order_stats')` — klient jest już
-- service_role, z komentarzem w kodzie wprost odsyłającym do §13.7
-- (`server-vercel.js:563`). Przypisanie klienta NIE jest już otwartym
-- pytaniem — decyzja użytkownika sprowadza się WYŁĄCZNIE do tego, czy
-- wykonać REVOKE EXECUTE dla ról klienckich (WARIANT 1, domyka to, co kod
-- już robi) czy przebudować funkcję na świadomie publiczny agregat
-- (WARIANT 2, wymaga dodatkowo zmiany kodu z powrotem na klienta publicznego).
-- Funkcja jest SECURITY INVOKER (inventory §4); jej search_path porządkuje
-- etap 12 niezależnie od tej decyzji.
--
-- UWAGA na kolejność względem etapu 9: po deny-all na orders funkcja INVOKER
-- wołana przez anon straci odczyt tabeli źródłowej niezależnie od EXECUTE —
-- endpoint statystyk przestanie zwracać dane dla klienta anon. To pożądany
-- fail-closed, ale musi być świadomy (plan §5, uwaga kolejnościowa).
-- ============================================================================

-- === WARIANT 1 — statystyki prywatne (rekomendacja spójna z deny-all) =======
-- Endpoint przechodzi na privateServerClient + autoryzację panelu;
-- funkcja zamknięta dla ról klienckich.
--
-- BEGIN;
-- DO $$
-- DECLARE fn record;
-- BEGIN
--   FOR fn IN
--     SELECT p.oid::regprocedure AS sig FROM pg_proc p
--     WHERE p.pronamespace = 'public'::regnamespace AND p.proname = 'get_order_stats'
--   LOOP
--     EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, anon, authenticated', fn.sig);
--     EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', fn.sig);
--   END LOOP;
-- END $$;
-- COMMIT;

-- === WARIANT 2 — agregat świadomie publiczny ================================
-- GRANT EXECUTE zostaje dla anon; wymaga DODATKOWO przebudowy funkcji na
-- SECURITY DEFINER z ustawionym search_path i ścisłym zakresem (bez PII),
-- inaczej po etapie 9 i tak zwróci odmowę/pustkę (INVOKER bez SELECT na orders).
-- Ta przebudowa to osobny, jawny projekt — nie zwykły GRANT.
--
-- (bez gotowego SQL — wariant wymaga projektu funkcji, nie samego grantu)
